name: convert

on:
  push:

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build book
        run: |-
          npm install -g md-to-pdf
          mkdir -p output
          cd docs
          echo; echo "Input Folder Listing"
          ls
          echo; echo "Generating PDF"
          for f in *.md; do cat $f; echo; done | md-to-pdf --stylesheet "../theme/style.css" > ../output/blue-paper.pdf
          cd ../output
          echo; echo "Output Folder Listing"
          ls
          cd ..

      - uses: actions/upload-artifact@v1
        with:
          name: output
          path: output
